### ISSUE TITLE
make zetteldeft a minor mode

### ISSUE THREAD

**Issue by mclearc** [EFLS/zetteldeft#1]
Thanks for this great set of functions! One possible enhancement would be to turn this into a minor mode. An advantage of doing so is that it would allow easy use of deft with multiple directories, only some of which are Zettelkästen. I have found one implementation of a minor mode [here](https://github.com/cszang/dotemacs/blob/master/lisp/zettelkasten.el). But I find your functions documented more clearly - so I'm trying to see how the two might work together. In any case, I appreciate your work 👏

**Comment by EFLS** [comment]
I'm not so sure anymore that this is useful – although that could be a sign of my `elisp` ignorance.

The way I use `zetteldeft`, I like to link to notes from any other (org-)file. If `zetteldeft` becomes a minor mode, then it would need to be activated separately. Also, I'm not so sure what it would add to the way `zetteldeft` is currently set up.

Other opinions welcome.

**Comment by mclearc** [comment]
Yeah - I know that I had suggested this originally, but I haven't found it a problem to just use it as a function set rather than a minor mode. As far as your use case goes, you could make a hook for org mode that invokes zetteldeft. But like you say, I'm not sure it would add much. The advantage of the minor mode would be in defining a key mapping, and autoloading functions, etc. But none of that seems absolutely necessary!

**Comment by EFLS** [comment]
I'm going to close this issue for now. If anyone wants to make the case for a minor mode, feel free to leave a comment still.
