### ISSUE TITLE
Two questions on Zetteldeft

### ISSUE THREAD

**Issue by AtomicNess123** [EFLS/zetteldeft#102]
1) Differences with org-roam
2) Is it possible to have links to specific parts of a file, not just the whole file? 
Thanks, excellent package.

**Comment by EFLS** [comment]
> Is it possible to have links to specific parts of a file, not just the whole file?

No, the way the links are implemented and searched for doesn't allow this. Links are always links to a note -- and notes are meant to be (relatively) short.

> Differences with org-roam

That's an incredible broad question, probably not best addressed here. Additionally, I haven't used Org-roam extensively so can't really compare.

But, some key points about Zetteldeft that could shed light on comparison with Org-roam:
 - All notes and links are plain text and resolved via such search. There is no database with links.
 - Notes are meant to be relatively short, cf. the 'atomic idea's' principle of the Zettelkasten method
 - Zetteldeft is not limited to Org-mode
 - There's limited automated backlinking. This is a deliberate design choice: users should make conscious links between notes.
 - That said, there is loads of room for automation thanks to Org code blocks. Check the zd-tutorial for some pointers

**Comment by AtomicNess123** [comment]
Thanks and apologies for the broad question. 
1. As for linking headings within files, wouldn't it work via `org-store-link` and `org-insert-link`?
2. When you say Zetteldeft has no database with links, I'm not sure I follow, but still files have their links, so is this important in the day to day note management?
3. By limited automated backlinking, you mean, links are not updates if I change the file location or rename it?

Thanks for the time!

**Comment by EFLS** [comment]
> As for linking headings within files, wouldn't it work via org-store-link and org-insert-link?

All Org-mode features still work, but those wouldn't be Zetteldeft links. To learn what Zetteldeft links are, check this [introduction](https://www.eliasstorms.net/zetteldeft/) or even better start with the zd-tutorial.

> When you say Zetteldeft has no database with links, I'm not sure I follow, but still files have their links, so is this important in the day to day note management?

Org-roam keeps track of links using a sort of database in the back end, AFAIK. 
Anyway I can only speak for Zetteldeft, and here files have unique identifiers which can be referred to (thus creating links). It's also explained in the introduction or the tutorial.

> links are not updates if I change the file location or rename it?

Links don't need to be updated if filenames or locations change (as long as it is within your Deft directory), as links work via the unique IDs in the filename (which is to say, those IDs should be stable, obviously). So renaming notes is no issue.

**Comment by AtomicNess123** [comment]
Thanks for all answers. 

> Links don't need to be updated if filenames or locations change (as long as it is within your Deft directory), as links work via the unique IDs in the filename (which is to say, those IDs should be stable, obviously). So renaming notes is no issue.

You mean, the automatic prefix should not be modified, but the text after them (in the file name) can be changed?

**Comment by EFLS** [comment]
Yes. Look at the documentation / introduction / tutorial for the nomenclature: IDs should be stable, but the rest of the filename can be changed. There's even functions to easily change filename and update the title in the note.
