### ISSUE TITLE
Define tags with in buffer settings #+

### ISSUE THREAD

**Issue by anthrolisp** [EFLS/zetteldeft#11]
Define tags with in buffer settings such as #+ztags: concept, name, etc. This way it can be ignored when exported.

**Comment by EFLS** [comment]
The idea of tags is that they can be defined anywhere in your note, not in one specific place only.

In any case, to ignore tags upon export, I use:

    # Tags #zetteldeft #meta

**Comment by anthrolisp** [comment]
Thanks!
