### ISSUE TITLE
#+CREATED: and #+LAST_MODIFIED properties

### ISSUE THREAD

**Issue by iburunat** [EFLS/zetteldeft#112]
Hi, and thanks a mil for this package.
Apologies in advance if this has been discussed elsewhere. Is there a way to include (like in org-roam) a #+created and #+last_modified properties at the header of the buffer (the latter would update automatically upon subsequent changes)?

```orgmode
#+TITLE: Zetteldeft is awesome
#+CREATED: [2021-05-08 Sat 21:39]
#+LAST_MODIFIED: [2021-05-08 Sat 21:39]
```
Thanks!

**Comment by iburunat** [comment]
Just found out how to add this:

`(setq zetteldeft-title-suffix "\n #+CREATED:\n #+LAST_MODIFIED:")`

However, only the created date seems to work. Not sure why.

```
#+TITLE: testing
 #+CREATED:
 #+LAST_MODIFIED:[2021-05-08 Sat 23:06]

```

**Comment by EFLS** [comment]
Hi, I think this has been asked in the past but can't seem to find that specific discussion.

Regards the creation date: by default Zetteldeft will generate a note ID with the creation date. You could thus refer to a note's ID to see when it was created?

Not sure how to achieve the last modified one, to be honest. Probably possible by writing some functions that would be executed each time a file is saved.

**Comment by iburunat** [comment]
> You could thus refer to a note's ID to see when it was created?

Brilliant :)
Actually, the "`LAST_MODIFIED`" property works fine, it gets updated upon each change.
Thanks!
