### ISSUE TITLE
Disable ID to clipboard

### ISSUE THREAD

**Issue by iburunat** [EFLS/zetteldeft#113]
My workflow is usually

1. I copy some text outside Emacs
2. I go to Emacs and do `M-x zetteldeft-new-file`
3. I aim to paste the copied text (but instead I have the ID in the clipboard)

Is it possible to disable this?
Thanks!

**Comment by EFLS** [comment]
Good suggestion! I'll look into it

**Comment by iburunat** [comment]
Thank you!

**Comment by EFLS** [comment]
This is now customizable with variable `zetteldeft-new-filename-to-kill-ring` (which is `nil` by default).

**Comment by iburunat** [comment]
Marvellous. Thank you.
