### ISSUE TITLE
Support deft subdirectories

### ISSUE THREAD

**Issue by anthrolisp** [EFLS/zetteldeft#12]
Including the ability to create new zd files in those sub-directories from the deft buffer, with something like /project X/...concept.org

**Comment by EFLS** [comment]
I don't think this would be a good idea, as it runs counter to the Zettelkasten idea of maintaining a flat file structure. Directories should be used as little as possible (or, preferably, not at all). This means that all structure should come from either tags (you can use both `#` and `@` if you need variety), or be maintained manually by including links to notes. The benefit of doing things manually, is that you are actively engaged with the content of your notes.

In any case, subdirectories are already supported by `deft` itself, just set `deft-recursive` to `t`.

In sum, I don't think this should be part of `zetteldeft`.

**Comment by anthrolisp** [comment]
The idea was inspired by both the way Zettlr (https://www.zettlr.com/) works as well as notdeft. The thought is to allow zetteldeft users some flexibility in how they decide to use or adopt the software.

**Comment by anthrolisp** [comment]
Related question: how hard would it be setup zetteldeft so that you had two separate zettelkastens? I understand this is not necessarily best practices, but I have a very large writing project that I'd like to keep separate from my main zettelkasten. Many thanks in advance!

**Comment by EFLS** [comment]
To link the issues: a simple switch between directories is indeed possible. See #20.

**Comment by EFLS** [comment]
I'm going to close this issue since (1) deft subdirectories are supported when deft is configured accordingly, and (2) switching between directories is possible per advice in #20.
