### ISSUE TITLE
Which special characters can be used to distinguish special tags?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [EFLS/zetteldeft#121]
I want to be more specific with some tags. It is like I want to tag the tags. Or someone would call it a tag hierarchie.

e.g. This are for zettel connection two zettels.
`#:typ:con`

e.g. This are for zettel about bibligraphic contexts.
`#:typ:bib`

But with `:` as first char the tags are not listed with <kbd>C-c</kbd> <kbd>d</kbd> <kbd>T</kbd>.
I tried `#typ:con` and `#typ.con`. Then only `#typ` appears in the list.
A `-` works as separator. But I would like to have something more "special" ;)

**Comment by EFLS** [comment]
So the request is to be able to use `-` in the tags? Have you tried modifying the `zetteldeft-tag-regex` to recognize such tags?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Not `-` because it works fine. But I want something more special like `:` or `::`.
I do not know about `zetteldeft-tag-regex`. It's default value is `"[#@][[:alnum:]_-]+"`.

No matter if I know how to use regex or not. As a emacs/zetteldeft novice I would prefer not to modify any defaults.

To be more specific with my request:

- Which chars are supported?
- Which "special" character would you recommend for such a use case?

**Comment by EFLS** [comment]
> Which chars are supported?

All the characters in the regexp. Tags should start with `#` or `@` and then use normal text characters, a `_` or a `-`. See also section 2.3 in the literate code at https://www.eliasstorms.net/zetteldeft/zetteldeft.html

> Which "special" character would you recommend for such a use case?

I'd use a `_` as a first character of your tag -- unless you want to change the `zetteldeft-regex`, then you can use whatever you configure.
