### ISSUE TITLE
FeatureRequest: Handle special characters in zettels filenames

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [EFLS/zetteldeft#123]
The problem:
Using "special" characters like `&`, `:` or `"` in a zettel's title while make this characters be part of the filename. In Linux this is not a problem but in windows it is.
In my use case I created such zettel in Debian 11 emacs and synced them via nextCloud to a Windows10 machine. Of course I got errors from nextCloud because of that chars.

Solution:
I do not have a concret technical solution because I do not really understand how title-to-filename-transformation or emacs itself works.
If you see a way it would be great to handle this automaticlly. For example special characters could be replaced by underlines `_` or something else. But doesn't this influence the way zettel titles are displayed in links on other zettels's?

Maybe you see a way?

Or just make an option to give a warning about forbidden chars in title/filename?

**Comment by EFLS** [comment]
> > My mistake! I meant to type `deft-file-naming-rules`.
> 
> IMHO it would improve the docu if you would have a special section about features and functionalities that does not come from `zetteldeft` but from `deft` or other emacs parts. Me as a user I do not think like a machine or in separated emacs modules/modes. I use zetteldeft not more. I want to change zetteldeft filenaming and of course I want to do that with zetteldeft. I does not come to my mind that another emacs module could be involved in such a basic feature.

Zetteldeft is specifially intended as expansion of Deft. In other words: Deft is the core of Zetteldeft (at least it is for now), so it doesn't make sense to me to duplicate configuration options.
