### ISSUE TITLE
zetteldeft-full-search-find-file: possibility to see results as we type keywords?

### ISSUE THREAD

**Issue by iburunat** [EFLS/zetteldeft#129]
Hi, I recently started using the new functions to find notes via full content search, excellent addition!

To use `zetteldeft-full-search-find-file` I must a priori set the keywords and then press enter to see a list of files containing those keywords. 

Now the improvement would be to have results appear (in the results buffer) as the user types keywords (the user could rectify or add more keywords depending on the list of resulting files for better filtering). Is this a feasible feature?

**Comment by localauthor** [comment]
You might try `[consult-grep](https://github.com/minad/consult)`, which does something like what you describe

**Comment by iburunat** [comment]
Thanks, is this similar to `helm-ag` or `helm-rg`? There are so many similar functions that I am confused about their scopes.

**Comment by EFLS** [comment]
Thanks for the suggestion, but I don't think it's feasible to include this with the current `-full-search` functions, seeing how they are implemented. But if someone achieves this by modifying the current `zetteldeft--full-search`, I'd be happy to include it. But for now I'm closing this issue.
