### ISSUE TITLE
Sorting of files in zetteldeft-find-file

### ISSUE THREAD

**Issue by AtomicNess123** [EFLS/zetteldeft#134]
Quick question: when using `zetteldeft-find-file`, is there a way to show the zetteldeft files in some sorting order? Right now they seem to be randomly sorted. It would be nice to have them alphabetically ordered or by date. Thanks!

**Comment by EFLS** [comment]
AFAIK sorting of candidates is not done by Zetteldeft, but by your completion engine. Zetteldeft relies on `completing-read`, so this really depends on which completion system you use in your Emacs setup.

**Comment by AtomicNess123** [comment]
I don't understand the syntax of the variable `completing-read,` it is too complex for me to customize.
