### ISSUE TITLE
Incompatibility with Org 9.5.5?

### ISSUE THREAD

**Issue by pefimo** [EFLS/zetteldeft#140]
Dear @EFLS,

I've updated some of my packages yesterday, ending up with Org 9.5.5 and the most recent Zettledeft. Since the update, auto-loading the module causes void function error on `org-dynamic-block-define` from [zetteldeft.org:2285](https://github.com/EFLS/zetteldeft/blame/master/zetteldeft.org#L2285).

Could you please recommend a version of Org that Zettledeft is known to work with? Or if you're working with the up-to-date version and do have the function, could you please give me a hint where it's defined?

Thank you for developing this wonderful utility. I think it is my most important tool at the moment.

**Comment by EFLS** [comment]
That's strange, I'm also on Org 9.5.5, and I don't think this is a recent change. Perhaps you load Zetteldeft before Org in your setup? (That might be something I need to take into account on my end.)

**Comment by pefimo** [comment]
Thank you so much @EFLS, I've just upgraded from melpa and the issue is indeed solved!
