### ISSUE TITLE
#+title should be capitalized by default

### ISSUE THREAD

**Issue by rotlaus** [EFLS/zetteldeft#18]
When creating a new zettel an org-mode title is inserted into the zettel uncapitalized (#+title:)
But Org-mode defines the title as uppercase (#+TITLE:). 
In the suggested deft setup it is hinted to configure deft to ignore the lowercase org-mode title, but in my opinion that is not the right way to go forward, it should be capitalized in the first place.

Opinions on this?

**Comment by EFLS** [comment]
Yes, you are right. This is my personal preference, but since the org-mode default is capitalized, I should at least make it customizable. Should be easy enough. I might look into this together with #17.

**Comment by EFLS** [comment]
This should be fixed now. Customizable and capitalized by default. See also #17.
