### ISSUE TITLE
make zetteldeft available on MELPA

### ISSUE THREAD

**Issue by trenkert** [EFLS/zetteldeft#2]
it would make installation and adoption much easier

**Comment by EFLS** [comment]
This could be a long-term goal, but currently it isn't even a real package yet. Also, I'm fairly new to `emacs` and `elisp`, so it might take some time until `zetteldeft` itself is up to par.

I should, however, think of a way to make it easier to install in the short term.

**Comment by EFLS** [comment]
I've changed some minor things, and `zetteldeft` should now be a package.

Adding it to MELPA is next on my list, but unfamiliar terrain for me. I'll look into this in the near future.

**Comment by krobbins** [comment]
I recently came across the "Distributing on MELPA" section of the blog post "Take Your Emacs to the Next Level by Writing Custom Packages" (https://spin.atomicobject.com/2016/05/27/write-emacs-package/) that may help.

**Comment by EFLS** [comment]
I've finally gotten around to making the necessary changes (cleaning up the code, fixing warnings with `checkdock` and `package-lint`), for it to be submitted to MELPA.

This also meant that I had to change the namespace from `zd-*` to `zetteldeft-*`. This will break configurations of users (mainly keybindings). Sorry about that! But we'll benefit in the long run.

**Comment by EFLS** [comment]
Finally available on MELPA! http://melpa.org/#/zetteldeft
