### ISSUE TITLE
Possible to have multiple zettelkastens?

### ISSUE THREAD

**Issue by anthrolisp** [EFLS/zetteldeft#20]
How difficult would it be to setup zetteldeft to work with two (or more) separate zettelkastens? I understand this is not necessarily best practice, but I have a very large writing project that I'd like to keep separate from my main zettelkasten. Many thanks in  advance!

**Comment by EFLS** [comment]
This is more related to `deft` than it is to `zetteldeft`.

Anyway, it should be easy for you to achieve something like this in your private setup: change the variable `deft-directory` and call `deft-refresh` afterwards. To let a simple function do that for you:

    (defun set-zd ()
      (interactive)
      (setq deft-directory "~/mydir")
      (deft-refresh))

**Comment by anthrolisp** [comment]
Wow. Perfect. Thank you!

**Comment by anthrolisp** [comment]
Awesome. Thank you!
I can switch into my second zd now. Curious about the best way to switch between them. Is there a simple way, to make the new function either switch back to the other, or else list a pre-set number of directories to select from?
Thanks again! Zetteldeft is an awesome package!

**Comment by EFLS** [comment]
The easiest would be to write two separate functions. Simply set the `deft-directory` variable accordingly. You could make a more complex function that prompts for a directory, but this is the simplest approach.

Glad to hear that `zetteldeft` is of use to you. That's my reason to share it: to contribute to the wonderful emacs community that I benefit so much from.

**Comment by anthrolisp** [comment]
Perfect. I created a hydra. Thank you again!

```
(defun zd-a ()
  (interactive)
(deft)
  (setq deft-directory "~/zd-a/")
  (deft-refresh))

(defun zd-b ()
(deft)
  (interactive)
  (setq deft-directory "~/zd-b/")
  (deft-refresh))

;(require 'hydra)
(defhydra zd-switch (nil nil :foreign-keys nil :hint nil :exit t)
  "
Open:
----------------------
_m_ A zettelkasten
_t_ B zettelkasten

_q_ quit"
  ("q" nil)
  ("a" zd-a)
  ("b" zd-b))
(global-set-key (kbd "<f9>") 'zd-switch/body)
```

**Comment by gklimowicz** [comment]
I do this between three Zettelkasten. I use functions, like the ones above, but also take the liberty of changing other settings:
```
(defun gk/nv ()
  (interactive)
  (let ((gc-cons-threshold most-positive-fixnum))
    (setq deft-directory "~/NVIDIA")
    (setq deft-recursive nil)
    (setq deft-file-limit 200)
    (setq zetteldeft-id-format "%Y%m%d-%H%M")
    (deft-refresh)))
```

Seems to work so far. (Since some of these have several thousand notes, I suspend garbage collection during the `deft-refresh`.)

**Comment by EFLS** [comment]
I've included these code snippets [in `zd-tutorial`](https://github.com/EFLS/zd-tutorial/blob/master/2020-07-08-2147%20Switching%20between%20Zettelkasten%20directories.org).
