### ISSUE TITLE
Feature Request: wikiword as tags

### ISSUE THREAD

**Issue by nthainguyen** [EFLS/zetteldeft#21]
I think it would be neat to have WikiWord as tags and set faces to such WikiWord (much like todo keyword). Sure it would be more work for user to write 2 capital letter than just a # symbol, but I think the presentation is much nicer for someone who like to drop Tags in the middle of the body text instead of in the top or middle of the notes (like myself).

**Comment by EFLS** [comment]
Can you elaborate on what WikiWords are? I'm not familiar with this feature.

**Comment by nthainguyen** [comment]
WikiWord is a feature of wikipedia. A WikiWord consists of two or more words with initial capitals, run together. It's a feature of wikipedia, wikipedia automatically convert WikiWords into links. 

What I requested is pretty much an additional syntax for Tag. I hope you get what I meant, English is not my 1st language.

**Comment by EFLS** [comment]
Tags are nothing special, they are just strings that make it easy to search for specific notes. You can place them anywhere in your notes.

So you can definitely already use WikiWords in your notes and retrieve those notes by searching for those specific WikiWords.
