### ISSUE TITLE
Suggest default keybindings

### ISSUE THREAD

**Issue by EFLS** [EFLS/zetteldeft#25]
To make this a package that is usable out of the box, I'd like to suggest some default keybindings.

Since I use `evil` myself, I'm looking for someone willing to share personal keybindings setup.

Where should these bindings go? What is the best used as a prefix?

**Comment by mclearc** [comment]
Here's my setup (using general):

```lisp
  (general-define-key
   :prefix "SPC"
   :non-normal-prefix "C-SPC"
   :states '(normal visual insert motion emacs)
   :keymaps 'override
   "z"  '(nil :wk "Zettelkasten")
   "zc" '(zd-search-current-id :wk "search current id")
   "zd" '(cpm/zettel-dired :wk "zettel dired view")
   "zf" '(zd-avy-file-search :wk "avy file search")
   "zF" '(zd-avy-file-search-ace-window :wk "avy file other window")
   "zI" '(zd-find-file-id-insert :wk "insert id")
   "zi" '(zd-find-file-full-title-insert :wk "insert full title")
   "zl" '(zd-avy-link-search :wk "avy link search")
   "zn" '(zd-new-file :wk "new file")
   "zN" '(zd-new-file-and-link :wk "new file & link")
   "zo" '(zd-find-file :wk "find file")
   "zr" '(zd-file-rename :wk "rename")
   "zR" '(deft-refresh :wk "refresh")
   "zs" '(zd-deft-new-search :wk "new search")
   "zS" '(zd-search-at-point :wk "search at point")
   "zt" '(zd-avy-tag-search :wk "avy tag search")
   "zT" '(zd-tag-buffer :wk "tag list")
   "z RET" '(zd-follow-link :wk "follow link at point")
   )

  (defun cpm/zettel-dired ()
    (interactive)
    (find-file "~/Dropbox/Notes/zettel")
    (peep-dired))

```

**Comment by EFLS** [comment]
Thanks. I see you also use general and a leader key. I’m still wondering what key sequences are best suggested in the guide for a ‘vanilla Emacs’ setup.

‘C-c z’ perhaps? I think normal letters are kept free for users to configure.

On 10 Nov 2019, at 18:25, Colin McLear <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's my setup (using general):

  (general-define-key
   :prefix "SPC"
   :non-normal-prefix "C-SPC"
   :states '(normal visual insert motion emacs)
   :keymaps 'override
   "z"  '(nil :wk "Zettelkasten")
   "zc" '(zd-search-current-id :wk "search current id")
   "zd" '(cpm/zettel-dired :wk "zettel dired view")
   "zf" '(zd-avy-file-search :wk "avy file search")
   "zF" '(zd-avy-file-search-ace-window :wk "avy file other window")
   "zI" '(zd-find-file-id-insert :wk "insert id")
   "zi" '(zd-find-file-full-title-insert :wk "insert full title")
   "zl" '(zd-avy-link-search :wk "avy link search")
   "zn" '(zd-new-file :wk "new file")
   "zN" '(zd-new-file-and-link :wk "new file & link")
   "zo" '(zd-find-file :wk "find file")
   "zr" '(zd-file-rename :wk "rename")
   "zR" '(deft-refresh :wk "refresh")
   "zs" '(zd-deft-new-search :wk "new search")
   "zS" '(zd-search-at-point :wk "search at point")
   "zt" '(zd-avy-tag-search :wk "avy tag search")
   "zT" '(zd-tag-buffer :wk "tag list")
   "z RET" '(zd-follow-link :wk "follow link at point")
   )

  (defun cpm/zettel-dired ()
    (interactive)
    (find-file "~/Dropbox/Notes/zettel")
    (peep-dired))

**Comment by EFLS** [comment]
Thanks. I see you also use general and a leader key. I’m still wondering what key sequences are best suggested in the guide for a ‘vanilla Emacs’ setup.

‘C-c z’ perhaps? I think normal letters are kept free for users to configure.

**Comment by mclearc** [comment]
Ah - I think I didn't quite understand that by 'out of the box' you meant vanilla emacs :). I think these are two pretty reliable discussions of emacs keybinding conventions: [mastering emacs](https://www.masteringemacs.org/article/mastering-key-bindings-emacs) and [Karl Voit](https://karl-voit.at/2018/07/08/emacs-key-bindings/). But yes, `C-c z` or `C-c C-z` seem like good candidates for prefixes

**Comment by EFLS** [comment]
I've expanded suggested keybindings for `C-c d`, in d6f0fc3.
