### ISSUE TITLE
Suggested spacemacs keys

### ISSUE THREAD

**Issue by brunosmmm** [EFLS/zetteldeft#33]
I've actually implemented zetteldeft support under the deft layer in spacemacs, and that has been merged into the develop branch: syl20bnr/spacemacs#13256.

I was thinking about submitting a pull request with updated documentation in the section with "suggested keybindings", however I started to second guess myself about what would be appropriate - mentioning enabling zetteldeft support in spacemacs, which comes with keybindings already setup (those are actually different from the currently suggested) AND/OR (keeping/removing) current suggestions.

Any ideas? If I get any pointers, I'll modify the docs accordingly and submit a PR.

Edit: reference PR instead of commit on spacemacs repo

**Comment by EFLS** [comment]
That's awesome! Please do make changes to the suggested keybindings section as you see fit. If there are much differences, maybe it is best indeed to add them under a separate heading. But the fact that there is a way to enable all of those with a single variable is very nice.

Could you also include an overview of the bindings, perhaps a table?
