### ISSUE TITLE
If you are able to customize the tag regex, shouldn't you also be able to customize the regex zd--get-thing-at-point uses for tags?

### ISSUE THREAD

**Issue by xoich** [EFLS/zetteldeft#36]
Hello, I was thinking of using `@#name` for tags because otherwise I get all those `#include` and `#if` from C notes.
But this way I can't use `zd--get-thing-at-point` to automatically search tags at point.

**Comment by EFLS** [comment]
Seems like it should indeed. I'll try to see how `zetteldeft--get-thing-at-point` can be made to use the `zetteldeft-tag-regex`.

By the way, since you mention `zd--`, make sure you use the latest version

**Comment by EFLS** [comment]
I've simplified `zetteldeft--get-thing-at-point` and tried to make sure it uses the `zetteldeft-tag-regex`.

I hope this fixes the issue. Let me know if it doesn't.
