### ISSUE TITLE
Generated Zettel IDs are not unique

### ISSUE THREAD

**Issue by pmiddend** [EFLS/zetteldeft#38]
I was just trying zetteldeft and created some notes, as well as linking notes to other notes. I ended up with the following list of nodes:

```
2020-03-29-1226 SD-WAN                                                                                 2020-03-29 12:27
2020-03-29-1226 Networking                                                                             2020-03-29 12:26
```

But shouldn't the ID be unique? I'm also having trouble with following links, probably because of the ID cluttering. Trying to follow the "Networking" link in "SD-WAN" doesn't work.

Edit: Just saw that it's simply the current time, accurate to minutes. Now, creating lots of small notes, probably while copying something written on paper, is a pretty common usecase I presume. Maybe using second-resolution would be a wiser choice? Or is this not related?

**Comment by EFLS** [comment]
Hi! You are right: when creating notes quickly, they will have the same ID, which can cause trouble.

One -- laborious -- work-around is to rename them manually.

Another is to change the IDs and to include seconds, as you suggested. You can do this by customizing `zetteldeft-id-format` and adding a `%S` in there. If I'm not mistaken, the default `zetteldeft-id-regex` should catch such a change as well, but make sure to check the documentation.

**Comment by pmiddend** [comment]
Thanks for the reply @EFLS, your suggestion worked perfectly.
