### ISSUE TITLE
How to configure deft for Spacemacs

### ISSUE THREAD

**Issue by mgarort** [EFLS/zetteldeft#39]
Hi,

I am new to Emacs (trying it out now for the first time because I want to create a zettelkasten with `zetteldeft`!). I am using the develop branch of Spacemacs and `emacs26`.

I am trying to install `zetteldeft` in the recommended way for Spacemacs users (following the tutorial on https://www.eliasstorms.net/zetteldeft/) but since I am completely new to Emacs I can't fully follow.

1. Should I first install `zetteldeft` and then activate the `deft` layer (i.e. in the installation tutorial, should I first follow step 1.2.1 and then step 1.2.2) or do I just have to activate the `deft` layer (i.e. should I only do step 1.2.2 of the tutorial)?
2. What files do I have to modify to configure `deft` as explained in section 3.2? The code for the configuration is given but I can't see where to paste it (I assume this is obvious to even the beginner Spacemacs user but I am not even at beginner level yet!)

Thanks a lot.

**Comment by EFLS** [comment]
It's been a while since I used Spacemacs, so I can't remember from the top of my head how to configure it precisely.

With regards to order: I don't think it matters that much. I think it makes sense to first call `deft`, then `zetteldeft`.

The code to configure goes wherever other Spacemacs configuration goes.

I think in the `user-config` section you can do something like

    ;; LOAD user-config FROM FILE
    (load "~/spacemacs/user-config.el")

And then store all of your configurations in that file.

Maybe @brunosmmm can share his insight?

**Comment by brunosmmm** [comment]
@mgarort , just enable the deft layer with the proper variables set, i.e. locate ```dotspacemacs-configuration-layers``` in your ```.spacemacs``` and add ```(deft :variables deft-zetteldeft t)``` to the list. That will automatically install ```deft``` and ```zetteldeft``` and load them in the correct order at startup.

For configuration, set the variables in your ```dotspacemacs/user-config```. For example, look at my configuration here: 

https://github.com/brunosmmm/dotfiles/blob/398b842a92bf4a1de1f9e96c982bea9ea6738dc4/dot/dot.spacemacs#L787-L789

**Comment by EFLS** [comment]
Thanks, I've added some notes in the documentation to make it a bit more clear.

**Comment by mgarort** [comment]
Hi,

I have been unable to configure it properly in Spacemacs, and Spacemacs seems to have a lot of issues open and to be in the middle of a change of version so I am not sure anymore if the problem is me or the problem is something else. Therefore I'm trying in Doom.

Thanks.

**Comment by mediapathic** [comment]
@mgarort I've just moved to Doom and would like to configure ZD for that, so I would be interested to hear your results.
