### ISSUE TITLE
Error installing package in doom emacs.

### ISSUE THREAD

**Issue by sunnyrahul25** [EFLS/zetteldeft#43]
I am beginner  and have never used emacs before.  I have installed deft and trying to install zetteldeft package but it is throwing package not found in repositories. I found the the package is there in MELPA but somehow doom emacs is not locating.

my config is.
```
packages.el 
(package! zettledeft)

config.el
(use-package! deft
  :commands (deft)
  :config (setq deft-directory "~/zk"
                deft-extensions '("org")))
(use-package! zetteldeft
  :after deft
  :init
)
```
Package error: (error Could not find package zettledeft in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))

If any doom user can help on this would be great.

**Comment by EFLS** [comment]
This seems more related to `doom` than to zetteldeft, but: did try `M-x package-refresh-contents`?

**Comment by sunnyrahul25** [comment]
reinstalled doomemacs, ran package-refresh-contents and  installed it via package-install command.
