### ISSUE TITLE
Help with getting zetteldeft-follow-link to work with Archive-style link indicators

### ISSUE THREAD

**Issue by avggeek** [EFLS/zetteldeft#44]
#### Description 
Hi,

I'm relatively new to Emacs & Zettelkasten so it's quite possible that there is a PEBKAC issue here so apologies in advance. But I've haven't been able to figure out what I'm doing wrong so am hoping to get some advice on what to fix.

I've been modifying some parts of zetteldeft so that I can use "The Archive" style links (similar to the discussion in #4) and have been successful with the actual link generation. However, I cannot get the ```zetteldeft-follow-link``` functions or deft-based functions like ```deft-open-preview``` to recognize the links. This is the case irrespective of whether I use just the Zettel ID or the full-link.

#### Reproduction guide 
- Start Spacemacs distribution of Emacs
- Change ```zetteldeft-link-indicator``` with ```(setq zetteldeft-link-indicator "[[")```
- Override ```zetteldeft-find-file-id-insert``` using ```(advice-add 'zetteldeft-find-file-id-insert :override #'my-private-layer/zetteldeft-find-file-id-insert)``` as the following function:
<details>
  <summary>zetteldeft-find-file-id-insert</summary>
  
```
(defun my-private-layer/zetteldeft-find-file-id-insert (file)
  "Find deft file FILE and insert a markdown-style link."
  (interactive (list
                (completing-read "File to insert id from: "
                                 (deft-find-all-files-no-prefix))))
  (insert (concat zetteldeft-link-indicator (zetteldeft--lift-id file) "]]")))

```
</details>

- Override ```zetteldeft-find-file-full-title-insert``` using ```(advice-add 'zetteldeft-find-file-full-title-insert :override #'my-private-layer/zetteldeft-find-file-full-title-insert``` as the following function:
<details>
  <summary>zetteldeft-find-file-full-title-insert</summary>
  
```
(defun my-private-layer/zetteldeft-find-file-full-title-insert (file)
  "find deft file file and insert a markdown-style link with title."
  (interactive (list
                (completing-read "file to insert full title from: "
                                 (deft-find-all-files-no-prefix))))
  (insert (concat zetteldeft-link-indicator (file-name-base file) "]]")))

```
</details>

- Generate a zettel in markdown format with links generated using the override functions as follows:
```
# foobaz
[[2020-04-12-1600]]
[[2020-04-12-1600 foobar]]
```
Where 2020-04-12-1600 foobar.md is the linked Zettel and is visible in Deft.

*Observed behaviour:* 
- ```zetteldeft-follow-link``` does not open the linked Zettel in new buffer, irrespective of whether cursor is at start of link or at start of Zettel ID/Name.

*Expected behaviour:* 
- Zetteldeft magic! ❤️ 

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 72f280dc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html helm auto-completion emacs-lisp git markdown org
      (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
      spell-checking emoji shell-scripts windows-scripts yaml dash chrome nginx
      (deft :variables deft-zetteldeft t)
      windows-defaults my-private-layer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by avggeek** [comment]
Further investigation:

- I modified ```zetteldeft-link-indicator``` to be a single character ```$``` using (setq zetteldeft-link-indicator "$")

*Observed behaviour:* 
- ```zetteldeft-follow-link``` now works with a Zettel link in the form ```$2020-04-12-1600 foobar``` or ```$2020-04-12-1600```

*Question:* 
- The function ```zetteldeft--get-thing-at-point``` states that it does recognize links between brackets (https://github.com/EFLS/zetteldeft/blob/master/zetteldeft.el#L78) and I can verify that link-builder-re does recognize ```[[2020-04-12-1600 foobar]]```. However, the function ```zetteldeft-follow-link``` still does not follow the link. Can anyone offer any ideas?

**Comment by EFLS** [comment]
I'll have to look into it. This is a good opportunity to further work on Markdown-styled zettelkasten like The Archive. I haven't used it with `[[` links myself.

Unfortunately, I'm busy with other work right now, but I'll see what I can do.

**Comment by EFLS** [comment]
A quick remark: `zetteldeft-follow-link` and `zetteldeft-avy-file-search` concatenate the `zetteldeft-link-indicator` and the `zetteldeft-id-regex` to generate a string, which serves as the regular expression that `avy` then tries to look for.

Now it could be that using `[[` as link indicator results in a problematic regular expression... Not sure what can be done about this, but it might be the cause.

**Comment by avggeek** [comment]
> A quick remark: `zetteldeft-follow-link` and `zetteldeft-avy-file-search` concatenate the `zetteldeft-link-indicator` and the `zetteldeft-id-regex` to generate a string, which serves as the regular expression that `avy` then tries to look for.
> 
> Now it could be that using `[[` as link indicator results in a problematic regular expression... Not sure yet what to do about this, but it might be the cause.

@EFLS I’m happy to try and debug this further to help narrow down the source of the issue, if you can point me to some good articles on Emacs debugging. Like I said at the start, Emacs newb here 🙂

**Comment by EFLS** [comment]
@avggeek Unfortunately, I'm far from an `elisp` expert myself, and one of the things I don't know much about is debugging something like this... I hope someone else can maybe make a suggestion on how to go about this.

What I usually do, is try and overwrite the existing `defun`s with something else and see what works :) Maybe try and overwrite the `zetteldeft-avy-file-search` function to use a different regular expression (one that matches your setup) and see how that works.

**Comment by avggeek** [comment]
@EFLS Yeah I noticed that @mclearc used a different function ```avy-goto-char-2``` in his comment here (https://github.com/EFLS/zetteldeft/issues/4#issuecomment-455879998) so let me see if create some other overrides as well.

**Comment by avggeek** [comment]
After turning on ```debug-on-entry``` and stepping through the code, it seems like the issue is not with ```zetteldeft-follow-link``` and ```zetteldeft-avy-file-search```, but rather with the call to ```deft-filter```. 
![emacs_owQ3Qn28ay](https://user-images.githubusercontent.com/66420/79350459-0ed01400-7f6a-11ea-848e-d6fb708836ed.png)

**Comment by EFLS** [comment]
I don't get what's happening here, as it looks like deft is called with the correct search string, i.e. the note's ID.

In any case, I noticed there are some issues with `zetteldeft-avy-file-search`. It relies on `avy-goto-char` while it might be better to use `avy-jump`.

I've tried `[[` as link indicator and it seems to work. Can you try to override `zetteldeft-avy-file-search` with the code below and see whether it helps?

    (defun zetteldeft-avy-file-search (&optional otherWindow)
      "Use `avy' to follow a zetteldeft link.
      Links are found via `zetteldeft-link-indicator'
      Open that file (in another window if OTHERWINDOW)."
        (interactive)
        (unless zetteldeft-link-indicator
          (user-error "Zetteldeft avy functions won't work when `zetteldeft-link-indicator' is nil"))
        (save-excursion
          (when (consp (avy-jump (concat
                  zetteldeft-link-indicator zetteldeft-id-regex)))
            (zetteldeft--search-filename
              (zetteldeft--lift-id (zetteldeft--get-thing-at-point)) otherWindow))))

**Comment by avggeek** [comment]
> 
> 
> I don't get what's happening here, as it looks like deft is called with the correct search string, i.e. the note's ID.
> 
> In any case, I noticed there are some issues with `zetteldeft-avy-file-search`. It relies on `avy-goto-char` while it might be better to use `avy-jump`.
> 
> I've tried `[[` as link indicator and it seems to work. Can you try to override `zetteldeft-avy-file-search` with the code below and see whether it helps?

@EFLS I'm happy to report that the function you have provided does indeed fix the issue! In fact, not only does ```zetteldeft-avy-file-search``` but I'm now able to use ```zetteldeft-follow-link``` correctly as well. Thank you so much for taking the time to help me fix this despite your busy schedule!

**Comment by EFLS** [comment]
> Thank you so much for taking the time to help me fix this despite your busy schedule!

Selectively procrastinating is a productivity trick 😄

The updated version will be part of the default codebase soon.

**Comment by avggeek** [comment]
> Selectively procrastinating is a productivity trick 😄
> 
> The updated version will be part of the default code soon.

Hi @EFLS I can confirm the newest version of the package does fix the issue without needing any overrides. So closing this issue - thank you again for the help!
