### ISSUE TITLE
How to install without use-package

### ISSUE THREAD

**Issue by Gahamelas** [EFLS/zetteldeft#46]
Sorry for the basic question. What line shall I add to my init if I have no use-package? Thanks.

**Comment by EFLS** [comment]
It's in the documentation, check section 1.2.3 here: https://www.eliasstorms.net/zetteldeft/

**Comment by Gahamelas** [comment]
Thanks, all clear. Only one question: "download the org-file and org-tangle it yourself. It should contain everything". What is org-file and org-tangle? Are these extra-packages I must add myself?

**Comment by EFLS** [comment]
Those packages are not needed, but allow you to generate the `.el` file from the documented `zetteldeft.org` files. But you can simply use the `zetteldeft.el` file if you are not familiar with Org-mode.

**Comment by Gahamelas** [comment]
I just installed the whole package via Melpa. I suppose that is correct?

**Comment by EFLS** [comment]
Yup, that's a full install as well.
