### ISSUE TITLE
graph function with tags

### ISSUE THREAD

**Issue by Gahamelas** [EFLS/zetteldeft#47]
Hi, 
Can the graphs be generated only for links or also for tags? My notes contain tags but not links.
Thank you,

**Comment by EFLS** [comment]
Not sure what you mean by this. How would you generate a graph if there are no links between notes?

**Comment by Gahamelas** [comment]
I was meaning, all notes that have the same #tag, would be linked together (bidirectionally). Does this make sense?

**Comment by EFLS** [comment]
That would lead to a very cluttered graph, I don't think it would be that useful. But I'm open to PRs if someone can make it work.

**Comment by Gahamelas** [comment]
That's true. Still, it would be interesting to see like a cloud if not a graph, of all the notes by tag. At least it would be nice to have it as a visualization option.

**Comment by EFLS** [comment]
Agreed, but not really feasible with `graphviz` I'm afraid. It's not high on my list of priorities, but I hope to come up with a new (perhaps interactive?) way of visualizing notes and their interconnections at some point in the future.

I'm closing this for now. If you want to start a discussion on alternative ways to visualize, feel free to open a new, specific issue.
