### ISSUE TITLE
keybinding problem

### ISSUE THREAD

**Issue by Gahamelas** [EFLS/zetteldeft#48]
Hi, I wonder if anybody has managed to set the keybindings for zettedeft:

```
; Remove C-c d that I want to use for me personally as a prefix.
(global-set-key (kbd "C-c d") nil) ;; was 'crux-duplicate-current-line'
(global-set-key (kbd "C-c d") 'zetteldeft-new-file)
```

As you see, by default Emacs has that binding assigned to `crux-duplicate-current-line`. I try to remove the binding first, and assigned it in my init file. However, this does not work. The binding continues to be assigned to `crux-duplicate-current-line.`

Any help welcome, 
Thanks, 
E

**Comment by EFLS** [comment]
I don't think this is related to Zetteldeft, but an issue with how you set keybindings.

My guess is that these bindings are overwritten later during startup. Try to figure out which package sets the `crux-*` binding, or try to make sure you set these keys only after the `crux-*` thing is loaded.

**Comment by Gahamelas** [comment]
Thanks, you are right. I will have a look more in detail.
