### ISSUE TITLE
Error: Symbol’s function definition is void

### ISSUE THREAD

**Issue by sbacelar** [EFLS/zetteldeft#49]
I have installed `zetteldeft` on Windows 10, `emacs 26.3` and I have received the following message error:

`Error (use-package): zetteldeft/:init: Symbol’s function definition is void: zetteldeft-set-classic-keybindings`

**Comment by EFLS** [comment]
Are you sure you have the latest version? Did you install via MELPA?

**Comment by sbacelar** [comment]
Yes. My version is from 20200415 and I installed it via MELPA.

**Comment by EFLS** [comment]
Ah, woops. Replace `:init` with `:config`.

I'll fix this in the documentation and the README.
