### ISSUE TITLE
Feature Request: option to create new notes as .md

### ISSUE THREAD

**Issue by mediapathic** [EFLS/zetteldeft#5]
For interoperability with The Archive, and general software-agnosticism. I'm doing most of my notes in md now, it works fine in deft and zetteldeft, and much better in The Archive. Zetteldeft makes it far more convenient to create new files in the flow of writing (thanks for that!), but I have to reformat and rename them to md when doing so. 

I admit I don't understand the internals well enough to understand how difficult this would be.

**Comment by mclearc** [comment]
I've modified the various zd functions to make them more friendly to markdown (and without the '§' convention). You can take a look at them in my config file [here](https://github.com/mclear-tools/dotemacs/blob/master/config.org#zetteldeft).

**Comment by EFLS** [comment]
Broad markdown support is something that would definitely make the package better. Up until now, I've mostly focused on what I personally use (org-mode all the way), but this is certainly something that I'll look into. I think I could include a general switch that would also disable any `org` related functionality.

**Comment by EFLS** [comment]
If you configure `deft-extensions` correctly, you can generate new notes in Markdown.

Take a look at the following note in `zd-tutorial` for more tips on Markdown notes in Zetteldeft: https://github.com/EFLS/zd-tutorial/blob/master/2020-04-17-1532%20Zetteldeft%20and%20Markdown.org
