### ISSUE TITLE
Create separate variable zetteldeft-directory

### ISSUE THREAD

**Issue by brittAnderson** [EFLS/zetteldeft#50]
I didn't know much about deft before finding your package, but I find deft quite handy on its own, and it is inconvenient to have to change and refresh the deft-directory value if I want to add a zettel entry, and then change back if I am just going to use plain deft. Is there a natural workaround at present to have a separate directory for zetteldeft that doesn't require this, or is the dependency on deft such that it isn't practical? Maybe the deft developer would consider adding a zetteldeft-directory variable to deft that could just point to 'deft-directory by default or nil, and be ignored by deft users, but set by zetteldeft users to allow us to have our zettel new files go in a separate location from our main text file directory (specifically I use a sub-directory of my ~/org/ directory for my zettels and I use deft to point to ~/org/)? 

Thanks for your excellent work.

**Comment by EFLS** [comment]
> Is there a natural workaround at present to have a separate directory for zetteldeft that doesn't require this, or is the dependency on deft such that it isn't practical?

Zetteldeft relies on deft for its search functions, so keeping your Zetteldeft notes completely separate from Deft is not feasible, I'm afraid.

I'm not sure I understand your use case entirely, but I can offer two suggestions:
 1. You can make sure Deft searches subdirectories in your `deft-directory` by setting `deft-recursive` to `t`. Or, reading your question again, maybe you already do this?
 1. You can make switching between two directories easier. Take a look at #20.

**Comment by EFLS** [comment]
Closing this for now, but feel free to restart the discussion if needed
