### ISSUE TITLE
Missing "(require 'ace-window)" in zetteldeft.org documentation

### ISSUE THREAD

**Issue by stampf** [EFLS/zetteldeft#57]
I tried to used C-c d F and got an error message. By reading the code, I've discovered that "require" inside the defun...
Furthermore, it seems 'thingatpt' is also needed. Wait, I've just found it's a builtin package :)

```
nicolas@benny:~/zetteldeft$ grep "(require" zetteldeft.el
(require 'deft)
(unless (require 'avy nil 'no-error)
(require 'thingatpt)
  (require 'ace-window)
```

**Comment by EFLS** [comment]
Yeah that's probably not best practice... I'll have to change that.

I didn't want to oblige people to install `ace-window`, but then again requiring inside a function might not be a good solution. Not sure what would be a good approach to avoid requiring `ace-window` from the start, but in the mean time I should require it similar to other packages.

**Comment by EFLS** [comment]
I tried figuring out the best practice by asking /r/emacs on Reddit. Not sure which answer to follow though...

https://www.reddit.com/r/emacs/comments/gtbfux/question_about_best_practice_for_require_when/

If anyone else has opinions on how to best handle this, please share

**Comment by gklimowicz** [comment]
I'm fine with including it as a top-level requirement.

**Comment by EFLS** [comment]
Yeah, I guess that is the cleanest option. Fixed.
