### ISSUE TITLE
newest release constantly not in zetteldeft territory

### ISSUE THREAD

**Issue by mediapathic** [EFLS/zetteldeft#6]
After upgrading to the newest release, I get "not in zetteldeft territory" when doing any "id" related function on any file. The directory of the files matches that variable as deft understands it.

**Comment by EFLS** [comment]
Strange. Could you give a more specific example of which functions you are trying out?

**Comment by rotlaus** [comment]
I had the same problem. In my case the deft-directory was defined as "~/sync/pm/notes". The buffer-filename has the Path mor like "c:/Users/adrian/sync/pm/notes", which is the same directory, but it does not seem to match.
I have set my deft-directory accordingly and now it works.

**Comment by EFLS** [comment]
The `zd--check` compares the path of the currently visited file to the path set in `deft-directory`.

I should probably make sure that during the check, `deft-directory` is expanded to an absolute path.

**Comment by EFLS** [comment]
@mediapathic Please check whether the latest commit fixes your problem.

**Comment by EFLS** [comment]
Yeah I guess that is a different issue, related to #4. I'll look into it and see whether I can replicate the issue.
