### ISSUE TITLE
Title insertion and file name hygiene

### ISSUE THREAD

**Issue by jeffvalk** [EFLS/zetteldeft#63]
First of all, thank you for Zetteldeft! 

Zetteldeft currently assumes that file names and titles are identical. This has a few drawbacks:

- If one uses a "/" in a new note's title, `emacs` tries to create a new directory, and note creation fails.
- If one configures `deft` to prevent this using `deft-file-naming-rules`, `zetteldeft` inserts titles into new notes with the ID prepended (see #41).

Might it be possible to permit file names that are "clean" versions of the title (e.g. a [slug](https://en.wikipedia.org/wiki/Clean_URL#Slug)), rather than verbatim?

For example:

- A new note titled "Zetteldeft File-Name/Title Relation" could be stored in a file named `2020-06-03-2328_zetteldeft_file-name_title_relation` using the following `deft` configuration:

    ```elisp
    (setq deft-file-naming-rules
          '((noslash . "_")
            (nospace . "_")
            (case-fn . downcase)))
    ```

- Since `zetteldeft-new-file` reads the intended title from interactive input, the full title could be passed to `zetteldeft--insert-title` directly rather than calling `zetteldeft--lift-file-title`. This would enable file name hygiene while allowing correct title insertion.

Am I missing something? Is the verbatim file name/title mapping a core design assumption?

**Comment by EFLS** [comment]
Thanks for sharing your thoughts!

>  Is the verbatim file name/title mapping a core design assumption?

It was an assumption albeit not a deliberate one, from back when this was a set of functions for personal use. But I agree that titles and filenames should be separated.

This is what PR #42 tries to achieve (although it's taking me some time to review the code). I think it uses a similar approach to what you are suggesting.

Please check the PR and share your thoughts on it!

**Comment by jeffvalk** [comment]
Oh excellent. Yes, PR #42 seems quite close to what I was thinking. Thanks for pointing me to it.

I tested the 8faaef60bb43847d08a60f2f2c1de1111ada35e4 version from that #42, and it behaves correctly for the example case I mentioned above (and similar). If I have any comments on the PR, I'll weigh in there.

**Comment by jeffvalk** [comment]
I noticed the updated contribution guidelines. Would you be interested in a more minimal PR to address this issue, which keeps with the project's literate/org-babel approach?

(I don't mean to step on anyone's efforts. Just looking to be efficient.)

**Comment by EFLS** [comment]
I've added the guidelines for future contributions, but these will not be used as criteria of any sort, they are just pointers for an easier workflow.

I think natdash is still working on it, so let's give it some time.

**Comment by jeffvalk** [comment]
Sounds good. I'll post my patch for his reference.

**Comment by EFLS** [comment]
I'll close this now that PR #42 is merged
