### ISSUE TITLE
great project! A few comments

### ISSUE THREAD

**Issue by cmorgan** [EFLS/zetteldeft#65]
The tags are not org-mode tags, is that correct? Did you try and use these? I wonder if there would be benefits to piggybacking on org tags?

I haven't dug into the linking too much, but would be cool if you could hide the zetteldeft style link and instead use a zetteldeft colored orgmode link. What do you think?

Cheers for the project.

**Comment by z3t0** [comment]
I am also interested in this! 

I use org-mode for my agenda system and previously for notes as well. It would be neat if the tags could be shared.

**Comment by z3t0** [comment]
That makes sense! I think tags can only be used on headlines.

I'm going to explore this further to see if maybe there's value in adding a more org-integrated workflow for some users. I'll report back on my findings.

Thank you for your work on this :smile:
