### ISSUE TITLE
What is the expected behave of C-c d I |(zetteldeft-find-file-full-title-insert FILE)?

### ISSUE THREAD

**Issue by touxstone** [EFLS/zetteldeft#73]
I still dunno what is the expected behave of `C-c d I |(zetteldeft-find-file-full-title-insert FILE)`. Okay, it's somehow described in the function-name but still, I keep getting nothing as a return for it (underdoing a kind of blind checking for every function, paced by the note-taking needs that arise while using the package is funny but sometimes I just got stuck and I've thought, better ask for help. Something like `in a scenery like this (see example), this is the doing of the function (see a return to the example)`. 
I'd appreciate any clue on this. Otherwise get sometimes stuck, in those functions I have managed to get under control, the package is just great.

**Comment by EFLS** [comment]
> Okay, it's somehow described in the function-name but still, I keep getting nothing as a return for it

Not sure what you mean by this.

In any case, your question made me notice that I completely skipped the creation of links in the tutorial. Here's what I just [added](https://github.com/EFLS/zd-tutorial/blob/master/2020-02-15-1626%20Zetteldeft%20basic%20commands.org):

> To **add a link** to an existing note, hit `C-c d i` (or `zetteldeft-find-file-id-insert`) and select a note from the prompt.
To include both the destination link and its title, use `C-c d I` (for `zetteldeft-find-file-full-title-insert).`

**Comment by touxstone** [comment]
so by `... not return for that command` I mean I got nothing insert(ed), but actually I got something, a message, whatever I do the retun I got reads `zetteldeft--lift-file-title: Opening input file: No such file or directory` though the file I mean to insert as a link does exist so I got some lost.

**Comment by EFLS** [comment]
Hmm, seems like a bug rather than an issue with documentation.

Have you customized your Zetteldeft setup? Can you share details on the name of the note you try to link to? Does it happen with any note?

**Comment by touxstone** [comment]
As seen below `C-c d I` kbd gives me as output: `Opening input file: No such file or directory`
![C-cdI-issues](https://user-images.githubusercontent.com/28830208/87159061-a36fb700-c2b8-11ea-814a-190480b315bf.gif)
-----
My setup, following recommendations:
```
(use-package deft
  :ensure t
  :custom
  (deft-extensions '("org" "md" "txt"))
  (deft-directory "~/Documents/my-orgth/Bitacora")
  (deft-use-filename-as-title t)
  (deft-recursive t))
(defun efls/deft-open-other ()
  (interactive)
  (deft-open-file-other-window t))
(defun efls/deft-open-preview ()
  (interactive)
  (deft-open-file-other-window))
(with-eval-after-load 'deft
  ;; (define-key deft-mode-map
  ;;   (kbd "<tab>") 'efls/deft-open-preview)
  (define-key deft-mode-map
    (kbd "<s-return>") 'efls/deft-open-other)
  ;; (define-key deft-mode-map
  ;;   (kbd "s-j") 'evil-next-line)
  ;; (define-key deft-mode-map (kbd "s-k") 'evil-previous-line)
  )                                     ;commented as I got those kbd already in use
(setq deft-strip-summary-regexp
      (concat "\\("
              "[\n\t]" ;; blank
              "\\|^#\\+[a-zA-Z_]+:.*$" ;;org-mode metadata
              "\\)"))

(use-package zetteldeft
  :ensure t
  :after deft
  :config (zetteldeft-set-classic-keybindings))
```

**Comment by EFLS** [comment]
I remember a problem with this function that should be fixed in this commit: eec57a61c5a153e8bb860b6db252be34cc31f1e2.

Are you sure you are using the latest version of Zetteldeft?

**Comment by EFLS** [comment]
Also, looking at your gif, for better integration with Org style links, you might be interested in [this note in the knowledge base](https://github.com/EFLS/zd-tutorial/blob/master/2020-03-25-0928%20Integration%20with%20org-link.org).

**Comment by touxstone** [comment]
Yep! updating worked!! Also thank you very much for the tip on the org-link integration.

**Comment by EFLS** [comment]
Glad to hear that!
