### ISSUE TITLE
zetteldeft-tag-buffer raises plist-get-keys function definition is void

### ISSUE THREAD

**Issue by ning-y** [EFLS/zetteldeft#80]
Hi! Thanks for writing a great package. I've just picked up emacs this week, but I've already spent maybe 50% of that time using zetteldeft.

I'm running into the error message (on the mini-buffer) which reads
> Symbol's function definition is void: plist-get-keys

When I try to call zetteldeft-tag-buffer interactively, either using `M-x zetteldeft-tag-buffer <RET>` or `C-c d T` (I have the recommended key bindings).

Can anyone help me with this? I'm don't really understand the results from Googling the exact term "plist-get-keys". I am on Debian, using emacs 27.1 (I compiled it from source, if that's a relevant piece of information).

**Comment by EFLS** [comment]
Hi, glad you like it.

Thanks for pointing out this issue. It seems that `plist-get-keys` is not a core function in Emacs (but rather part of `doi-utils.el`), so perhaps not the best choice. I'll look into it to see how I can resolve this!

**Comment by EFLS** [comment]
Kept bugging me, so I productively procrastinated what I should be doing and came up with an easy fix, part of 2b69b35a279470e9e3c8a0ff23264e606bf3bd42

Let me know if it works!

**Comment by ning-y** [comment]
Thank you! I'll probably wait to update it from MELPA because I'm still honestly quite clueless as to how to manually update packages.

**Comment by ning-y** [comment]
It works! Thanks very much for the quick response!
