### ISSUE TITLE
`zetteldeft-new-file-and-backlink` does not use `zetteldeft-link-suffix` for backlinks

### ISSUE THREAD

**Issue by fitzgen** [EFLS/zetteldeft#83]
> Aside: I've been using zetteldeft for a day now and it is really sweet! Thanks for making this and writing a great tutorial and tons of docs!

### Steps to reproduce

* Use a non-empty `zetteldeft-link-suffix`
* `C-c d B` (or `M-x zetteldeft-new-file-and-backlink RET`)
* Enter a new name
* `RET`

### Expected result

The `Backlink: ...` uses `zetteldeft-link-suffix`; eg if you are in markdown mode and using `[[`/`]]` prefix and suffix, you get `Backlink: [[id]] Title`

### Actual result

The suffix is missing, so you get `Backlink: [[id Title` with no `]]`

**Comment by EFLS** [comment]
Whoops, seems like something I forgot. I’m away from the computer for a couple of days but should be an quick fix when I get back.

**Comment by EFLS** [comment]
I just pushed a fix. Should be on MELPA soon. Let me know whether it works. And thanks for the excellent bug report!

**Comment by fitzgen** [comment]
Thanks for the quick fix!
