### ISSUE TITLE
Feature request: customize list syntax used by `zetteldeft-insert-list-links[-missing]`

### ISSUE THREAD

**Issue by fitzgen** [EFLS/zetteldeft#85]
Right now it always produces lists with <code>&nbsp;-</code> as the list syntax, e.g.:

```
 - [[id]] one
 - [[id]] two
```

I'm using zetteldeft with markdown files, and while the above works, it is (a) generally more idiomatic for markdown to either have zero or two spaces before the `-` and (b) I also happen to prefer to use `*` for lists although I've frequently seen both in the wild.

Would you be open to supporting a variable that customizes the list syntax? If so, I can try whipping up a PR.

**Comment by EFLS** [comment]
Hi, I sure am open to such improvements and customisation! PR more than welcome. 

What would this look like? A customisable string?

**Comment by fitzgen** [comment]
I was imagining a variable that would be a list prefix string, and by default would be " -". Does that sound reasonable?

**Comment by EFLS** [comment]
Sounds perfect. I look forward to a PR. If you can, make changes in the .org document as well (don’t feel obliged to write documentation — I can add that later).
