### ISSUE TITLE
Enable insertion of title line when renaming note

### ISSUE THREAD

**Issue by jeffvalk** [EFLS/zetteldeft#97]
Particularly for importing/promoting non-zetteldeft notes into a zettelkasten, it would be useful to allow (optional) insertion of a title line when renaming a note. Currently, renaming a note updates any existing title, but ignores a missing title.

**Comment by EFLS** [comment]
Many thanks for the PR!

**Comment by jeffvalk** [comment]
Of course! Thanks for pulling!
